/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 chair.glb -t 
*/

import * as THREE from 'three';
import React, { useRef } from 'react';
import { useGLTF } from '@react-three/drei';
import { GLTF } from 'three-stdlib';
import { GLTFResult } from './types';

const Chair = (props: JSX.IntrinsicElements['group']) => {
  const { nodes, materials } = useGLTF('public/models/chair.glb') as GLTFResult;
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]} scale={100}>
        <mesh
          geometry={nodes.OfficeChair_1.geometry}
          material={materials.Grey}
        />
        <mesh
          geometry={nodes.OfficeChair_2.geometry}
          material={materials.Black}
        />
        <mesh
          geometry={nodes.OfficeChair_3.geometry}
          material={materials.Chair}
        />
      </group>
    </group>
  );
};
export default Chair;
useGLTF.preload('/chair.glb');
